#### Get list from server
GET http://localhost:8000/api/bucket-lists


#### POST data to server
POST  http://localhost:8000/api/bucket-lists
#header of the request
Content-Type: application/json

 #body of the request,there should be gap between header and body
{
    "title": "Bungee Jumping",
    "description": "It has multiple locations in Australia and Nepal.",
    "category": "Adventure",
    "status": "Not Completed",
    "location": "Bhote Koshi",
    "cost": "10000",
    "owner": "Sujan"
}

#### PATCH data in server
PATCH   http://localhost:8000/api/bucket-lists
#header of the request
Content-Type: application/json

 #body of the request,there should be gap between header and body
{
    "id":"66287ab9e1b1444409cb3ae7",
    "title": "Bungee Jumping",
    "description": "It has multiple locations in Australia and Nepal.",
    "category": "Adventure",
    "status": "Not Completed",    
    "location": "Sun Koshi",     
    "cost": "15000",
    "owner": "Thapaji" 
}

#### DELETE data in server
DELETE http://localhost:8000/api/bucket-lists
#header of the request
Content-Type: application/json 

 #body of the request,there should be gap between header and body
{
    "ids":"662982be2509e06e1df6fca5" 
}